-- Chạy script này nếu DMBO_ROLE đã tạo từ V2 chưa có cột ROLE_LEVEL
ALTER TABLE DMBO_ROLE ADD (
    ROLE_LEVEL NUMBER(5) DEFAULT 99 NOT NULL
);

UPDATE DMBO_ROLE SET ROLE_LEVEL = 0 WHERE UPPER(ROLE_CODE) = 'SUPER_ADMIN';
UPDATE DMBO_ROLE SET ROLE_LEVEL = 1 WHERE UPPER(ROLE_CODE) = 'ADMIN';
UPDATE DMBO_ROLE SET ROLE_LEVEL = 2 WHERE UPPER(ROLE_CODE) = 'OPERATOR';
UPDATE DMBO_ROLE SET ROLE_LEVEL = 3 WHERE UPPER(ROLE_CODE) = 'VIEWER';

CREATE INDEX IX_DMBO_ROLE_LEVEL ON DMBO_ROLE (ROLE_LEVEL);

COMMIT;
