-- ============================================================
-- Seed first SUPER_ADMIN user for BackOffice login
-- Run AFTER DM_BACKOFFICE_AUTH_RBAC_V2_ORACLE.sql
--
-- Default credentials (change password after first login):
--   Username: admin
--   Password: Admin@123
--
-- PASSWORD_HASH generated by tools/GeneratePasswordHash (ASP.NET PasswordHasher).
-- To use another password:
--   dotnet run --project ../tools/GeneratePasswordHash -- "YourNewPassword"
-- ============================================================

INSERT INTO DMBO_USER (
    USER_NAME,
    FULL_NAME,
    EMAIL,
    STATUS,
    PASSWORD_HASH,
    ROLE_ID,
    IS_PASSWORD_CHANGED,
    CREATED_USER
)
SELECT
    'admin',
    N'Super Administrator',
    'admin@digimerchant.local',
    1,
    'AQAAAAIAAYagAAAAEDrXFcdh4fQI7Q7zcNXFfa7SEKvTEATu4qnQHzTvxlQ7ZrQeBFQ2grwkp1Eo/VDd4Q==',
    R.ROLE_ID,
    0,
    'SYSTEM'
FROM DMBO_ROLE R
WHERE UPPER(R.ROLE_CODE) = 'SUPER_ADMIN'
  AND NOT EXISTS (
      SELECT 1 FROM DMBO_USER U WHERE UPPER(U.USER_NAME) = 'ADMIN'
  );

COMMIT;

-- Verify:
-- SELECT U.USER_ID, U.USER_NAME, U.STATUS, R.ROLE_CODE
-- FROM DMBO_USER U
-- JOIN DMBO_ROLE R ON R.ROLE_ID = U.ROLE_ID
-- WHERE UPPER(U.USER_NAME) = 'ADMIN';
