-- ============================================================
-- DigiMerchant - Banner config (Oracle)
-- Chạy thủ công. Không dùng EF migration.
-- ============================================================

CREATE TABLE DM_BANNER_CONFIG (
    BANNER_ID              NUMBER(19)      NOT NULL,
    ENVIRONMENT_CODE       VARCHAR2(20)    NOT NULL,
    GROUP_CODE             VARCHAR2(100)   NOT NULL,
    CATEGORY_CODE          VARCHAR2(100),
    TYPE_CODE              VARCHAR2(100),
    TITLE                  NVARCHAR2(255),
    BODY                   NVARCHAR2(1000),
    IMAGE_URL              VARCHAR2(1000),
    BUTTON_TEXT            NVARCHAR2(100),
    ACTION_TYPE            VARCHAR2(50),
    FUNCTION_CODE          VARCHAR2(150),
    DEEP_LINK              VARCHAR2(1000),
    WEB_URL                VARCHAR2(1000),
    MOBILE_FUNCTION_CODES  CLOB,
    ASPECT_RATIO_CODE      VARCHAR2(20),
    ASPECT_RATIO_VALUE     NUMBER(10,4),
    IMAGE_WIDTH_PX         NUMBER(10),
    IMAGE_HEIGHT_PX        NUMBER(10),
    RENDER_MODE            VARCHAR2(50),
    PRIORITY               NUMBER(10)      DEFAULT 0 NOT NULL,
    STATUS                 VARCHAR2(20)    DEFAULT 'DRAFT' NOT NULL,
    START_TIME             TIMESTAMP(6),
    END_TIME               TIMESTAMP(6),
    APP_VERSION            VARCHAR2(50),
    PLATFORM               VARCHAR2(30)    DEFAULT 'ALL' NOT NULL,
    LOGIN_REQUIRED         NUMBER(1)       DEFAULT 1 NOT NULL,
    TRACKING_CODE          VARCHAR2(100),
    CREATED_BY             VARCHAR2(100),
    CREATED_AT             TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY             VARCHAR2(100),
    UPDATED_AT             TIMESTAMP(6),
    CONSTRAINT PK_DM_BANNER_CONFIG PRIMARY KEY (BANNER_ID),
    CONSTRAINT CK_DM_BANNER_ENV CHECK (ENVIRONMENT_CODE IN ('UAT', 'PILOT', 'PROD')),
    CONSTRAINT CK_DM_BANNER_STATUS CHECK (STATUS IN ('DRAFT', 'ACTIVE', 'INACTIVE', 'EXPIRED', 'DELETED')),
    CONSTRAINT CK_DM_BANNER_PLATFORM CHECK (PLATFORM IN ('ALL', 'IOS', 'ANDROID')),
    CONSTRAINT CK_DM_BANNER_LOGIN_REQ CHECK (LOGIN_REQUIRED IN (0, 1)),
    CONSTRAINT CK_DM_BANNER_RENDER_MODE CHECK (
        RENDER_MODE IS NULL OR RENDER_MODE IN ('FIT_WIDTH', 'CENTER_CROP', 'CONTAIN', 'COVER')
    ),
    CONSTRAINT CK_DM_BANNER_ACTION_TYPE CHECK (
        ACTION_TYPE IS NULL OR ACTION_TYPE IN ('NONE', 'NATIVE', 'DEEPLINK', 'WEBVIEW', 'EXTERNAL_BROWSER')
    )
);

CREATE SEQUENCE SEQ_DM_BANNER_CONFIG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_DM_BANNER_CONFIG_BI
BEFORE INSERT ON DM_BANNER_CONFIG
FOR EACH ROW
BEGIN
    IF :NEW.BANNER_ID IS NULL THEN
        SELECT SEQ_DM_BANNER_CONFIG.NEXTVAL INTO :NEW.BANNER_ID FROM DUAL;
    END IF;
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

CREATE INDEX IX_DM_BANNER_ENV_STATUS ON DM_BANNER_CONFIG (ENVIRONMENT_CODE, STATUS);
CREATE INDEX IX_DM_BANNER_ENV_GROUP_CAT ON DM_BANNER_CONFIG (ENVIRONMENT_CODE, GROUP_CODE, CATEGORY_CODE);
CREATE INDEX IX_DM_BANNER_ENV_TIME ON DM_BANNER_CONFIG (ENVIRONMENT_CODE, START_TIME, END_TIME);
CREATE INDEX IX_DM_BANNER_ENV_PRIORITY ON DM_BANNER_CONFIG (ENVIRONMENT_CODE, PRIORITY);
CREATE INDEX IX_DM_BANNER_ENV_LOGIN ON DM_BANNER_CONFIG (ENVIRONMENT_CODE, LOGIN_REQUIRED, STATUS);
CREATE UNIQUE INDEX UX_DM_BANNER_ENV_TRACKING_CODE ON DM_BANNER_CONFIG (ENVIRONMENT_CODE, TRACKING_CODE);

-- RBAC (DMBO_FUNCTION)
INSERT INTO DMBO_FUNCTION (FUNCTION_CODE, FUNCTION_NAME, FUNCTION_LEVEL, FUNCTION_URL, FUNCTION_ORDER, PARENT_ID, FUNCTION_DISPLAY, STATUS, CREATED_BY)
SELECT 'BANNER_MANAGEMENT', N'Cấu hình banner', 1, '/banners', 30, NULL, 1, 'ACTIVE', 'SYSTEM' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'BANNER_MANAGEMENT');

INSERT INTO DMBO_FUNCTION (FUNCTION_CODE, FUNCTION_NAME, FUNCTION_LEVEL, FUNCTION_URL, FUNCTION_ORDER, PARENT_ID, FUNCTION_DISPLAY, STATUS, CREATED_BY)
SELECT 'BANNER_CREATE', N'Tạo banner', 2, NULL, 31,
       (SELECT FUNCTION_ID FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'BANNER_MANAGEMENT'),
       0, 'ACTIVE', 'SYSTEM' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'BANNER_CREATE');

INSERT INTO DMBO_FUNCTION (FUNCTION_CODE, FUNCTION_NAME, FUNCTION_LEVEL, FUNCTION_URL, FUNCTION_ORDER, PARENT_ID, FUNCTION_DISPLAY, STATUS, CREATED_BY)
SELECT 'BANNER_UPDATE', N'Cập nhật banner', 2, NULL, 32,
       (SELECT FUNCTION_ID FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'BANNER_MANAGEMENT'),
       0, 'ACTIVE', 'SYSTEM' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'BANNER_UPDATE');

INSERT INTO DMBO_FUNCTION (FUNCTION_CODE, FUNCTION_NAME, FUNCTION_LEVEL, FUNCTION_URL, FUNCTION_ORDER, PARENT_ID, FUNCTION_DISPLAY, STATUS, CREATED_BY)
SELECT 'BANNER_DELETE', N'Xóa banner', 2, NULL, 33,
       (SELECT FUNCTION_ID FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'BANNER_MANAGEMENT'),
       0, 'ACTIVE', 'SYSTEM' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'BANNER_DELETE');

INSERT INTO DMBO_FUNCTION (FUNCTION_CODE, FUNCTION_NAME, FUNCTION_LEVEL, FUNCTION_URL, FUNCTION_ORDER, PARENT_ID, FUNCTION_DISPLAY, STATUS, CREATED_BY)
SELECT 'BANNER_CHANGE_STATUS', N'Đổi trạng thái banner', 2, NULL, 34,
       (SELECT FUNCTION_ID FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'BANNER_MANAGEMENT'),
       0, 'ACTIVE', 'SYSTEM' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'BANNER_CHANGE_STATUS');

INSERT INTO DMBO_ROLE_FUNC (ROLE_ID, FUNCTION_ID, CREATE_USER)
SELECT R.ROLE_ID, F.FUNCTION_ID, 'SYSTEM'
FROM DMBO_ROLE R
JOIN DMBO_FUNCTION F ON UPPER(F.FUNCTION_CODE) IN (
    'BANNER_MANAGEMENT', 'BANNER_CREATE', 'BANNER_UPDATE', 'BANNER_DELETE', 'BANNER_CHANGE_STATUS'
)
WHERE UPPER(R.ROLE_CODE) = 'SUPER_ADMIN'
  AND NOT EXISTS (
      SELECT 1 FROM DMBO_ROLE_FUNC RF
      WHERE RF.ROLE_ID = R.ROLE_ID AND RF.FUNCTION_ID = F.FUNCTION_ID
  );

COMMIT;
