-- Chạy khi DB đã có MIN_APP_VERSION / MAX_APP_VERSION (migrate sang APP_VERSION)
-- Bỏ qua nếu đã tạo bảng mới từ DM_BANNER_CONFIG_ORACLE.sql / DM_ICON_CONFIG_ORACLE.sql (đã có APP_VERSION)

-- Banner
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE DM_BANNER_CONFIG ADD APP_VERSION VARCHAR2(50)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF; -- column already exists
END;
/

UPDATE DM_BANNER_CONFIG
SET APP_VERSION = MIN_APP_VERSION
WHERE APP_VERSION IS NULL AND MIN_APP_VERSION IS NOT NULL;

-- Icon
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE DM_ICON_CONFIG ADD APP_VERSION VARCHAR2(50)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

UPDATE DM_ICON_CONFIG
SET APP_VERSION = MIN_APP_VERSION
WHERE APP_VERSION IS NULL AND MIN_APP_VERSION IS NOT NULL;

-- Tùy chọn: xóa cột cũ sau khi verify
-- ALTER TABLE DM_BANNER_CONFIG DROP COLUMN MIN_APP_VERSION;
-- ALTER TABLE DM_BANNER_CONFIG DROP COLUMN MAX_APP_VERSION;
-- ALTER TABLE DM_ICON_CONFIG DROP COLUMN MIN_APP_VERSION;
-- ALTER TABLE DM_ICON_CONFIG DROP COLUMN MAX_APP_VERSION;
