-- ============================================================
-- DigiMerchant - Icon config (Oracle)
-- Chạy thủ công. Không dùng EF migration.
-- Category là list suy ra từ icon (GROUP/CATEGORY/TYPE), không có bảng riêng.
-- ============================================================

CREATE TABLE DM_ICON_CONFIG (
    ICON_ID             NUMBER(19)      NOT NULL,
    ENVIRONMENT_CODE    VARCHAR2(20)    NOT NULL,
    GROUP_CODE          VARCHAR2(100)   NOT NULL,
    CATEGORY_CODE       VARCHAR2(100),
    TYPE_CODE           VARCHAR2(100),
    TITLE               NVARCHAR2(255)  NOT NULL,
    SUBTITLE            NVARCHAR2(500),
    ICON_URL            VARCHAR2(1000)  NOT NULL,
    ICON_SELECTED_URL   VARCHAR2(1000),
    ICON_DISABLED_URL   VARCHAR2(1000),
    BACKGROUND_COLOR    VARCHAR2(30),
    TEXT_COLOR          VARCHAR2(30),
    FUNCTION_CODE       VARCHAR2(150),
    DEEP_LINK           VARCHAR2(1000),
    WEB_URL             VARCHAR2(1000),
    ACTION_TYPE         VARCHAR2(50),
    BADGE_TYPE          VARCHAR2(50),
    BADGE_TEXT          NVARCHAR2(100),
    BADGE_COLOR         VARCHAR2(30),
    BADGE_BG_COLOR      VARCHAR2(30),
    BADGE_START_TIME    TIMESTAMP(6),
    BADGE_END_TIME      TIMESTAMP(6),
    PRIORITY            NUMBER(10)      DEFAULT 0 NOT NULL,
    GRID_SPAN           NUMBER(5)       DEFAULT 1 NOT NULL,
    STATUS              VARCHAR2(20)    DEFAULT 'DRAFT' NOT NULL,
    START_TIME          TIMESTAMP(6),
    END_TIME            TIMESTAMP(6),
    APP_VERSION         VARCHAR2(50),
    PLATFORM            VARCHAR2(30)    DEFAULT 'ALL' NOT NULL,
    LOGIN_REQUIRED      NUMBER(1)       DEFAULT 1 NOT NULL,
    TRACKING_CODE       VARCHAR2(100),
    CREATED_BY          VARCHAR2(100),
    CREATED_AT          TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY          VARCHAR2(100),
    UPDATED_AT          TIMESTAMP(6),
    CONSTRAINT PK_DM_ICON_CONFIG PRIMARY KEY (ICON_ID),
    CONSTRAINT CK_DM_ICON_ENV CHECK (ENVIRONMENT_CODE IN ('UAT', 'PILOT', 'PROD')),
    CONSTRAINT CK_DM_ICON_STATUS CHECK (STATUS IN ('DRAFT', 'ACTIVE', 'INACTIVE', 'EXPIRED', 'DELETED')),
    CONSTRAINT CK_DM_ICON_PLATFORM CHECK (PLATFORM IN ('ALL', 'IOS', 'ANDROID')),
    CONSTRAINT CK_DM_ICON_LOGIN_REQ CHECK (LOGIN_REQUIRED IN (0, 1)),
    CONSTRAINT CK_DM_ICON_ACTION_TYPE CHECK (
        ACTION_TYPE IS NULL OR ACTION_TYPE IN ('NONE', 'NATIVE', 'DEEPLINK', 'WEBVIEW', 'EXTERNAL_BROWSER')
    )
);

CREATE SEQUENCE SEQ_DM_ICON_CONFIG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_DM_ICON_CONFIG_BI
BEFORE INSERT ON DM_ICON_CONFIG
FOR EACH ROW
BEGIN
    IF :NEW.ICON_ID IS NULL THEN
        SELECT SEQ_DM_ICON_CONFIG.NEXTVAL INTO :NEW.ICON_ID FROM DUAL;
    END IF;
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

CREATE INDEX IX_DM_ICON_ENV_STATUS ON DM_ICON_CONFIG (ENVIRONMENT_CODE, STATUS);
CREATE INDEX IX_DM_ICON_ENV_FUNCTION ON DM_ICON_CONFIG (ENVIRONMENT_CODE, FUNCTION_CODE);
CREATE INDEX IX_DM_ICON_ENV_GROUP_CATEGORY ON DM_ICON_CONFIG (ENVIRONMENT_CODE, GROUP_CODE, CATEGORY_CODE);
CREATE INDEX IX_DM_ICON_ENV_TIME ON DM_ICON_CONFIG (ENVIRONMENT_CODE, START_TIME, END_TIME);
CREATE INDEX IX_DM_ICON_ENV_PRIORITY ON DM_ICON_CONFIG (ENVIRONMENT_CODE, PRIORITY);
CREATE INDEX IX_DM_ICON_ENV_LOGIN ON DM_ICON_CONFIG (ENVIRONMENT_CODE, LOGIN_REQUIRED, STATUS);
CREATE UNIQUE INDEX UX_DM_ICON_ENV_TRACKING_CODE ON DM_ICON_CONFIG (ENVIRONMENT_CODE, TRACKING_CODE);

-- RBAC (DMBO_FUNCTION)
INSERT INTO DMBO_FUNCTION (FUNCTION_CODE, FUNCTION_NAME, FUNCTION_LEVEL, FUNCTION_URL, FUNCTION_ORDER, PARENT_ID, FUNCTION_DISPLAY, STATUS, CREATED_BY)
SELECT 'ICON_MANAGEMENT', N'Cấu hình icon', 1, '/icons', 40, NULL, 1, 'ACTIVE', 'SYSTEM' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'ICON_MANAGEMENT');

INSERT INTO DMBO_FUNCTION (FUNCTION_CODE, FUNCTION_NAME, FUNCTION_LEVEL, FUNCTION_URL, FUNCTION_ORDER, PARENT_ID, FUNCTION_DISPLAY, STATUS, CREATED_BY)
SELECT 'ICON_CREATE', N'Tạo icon', 2, NULL, 41,
       (SELECT FUNCTION_ID FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'ICON_MANAGEMENT'),
       0, 'ACTIVE', 'SYSTEM' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'ICON_CREATE');

INSERT INTO DMBO_FUNCTION (FUNCTION_CODE, FUNCTION_NAME, FUNCTION_LEVEL, FUNCTION_URL, FUNCTION_ORDER, PARENT_ID, FUNCTION_DISPLAY, STATUS, CREATED_BY)
SELECT 'ICON_UPDATE', N'Cập nhật icon', 2, NULL, 42,
       (SELECT FUNCTION_ID FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'ICON_MANAGEMENT'),
       0, 'ACTIVE', 'SYSTEM' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'ICON_UPDATE');

INSERT INTO DMBO_FUNCTION (FUNCTION_CODE, FUNCTION_NAME, FUNCTION_LEVEL, FUNCTION_URL, FUNCTION_ORDER, PARENT_ID, FUNCTION_DISPLAY, STATUS, CREATED_BY)
SELECT 'ICON_DELETE', N'Xóa icon', 2, NULL, 43,
       (SELECT FUNCTION_ID FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'ICON_MANAGEMENT'),
       0, 'ACTIVE', 'SYSTEM' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'ICON_DELETE');

INSERT INTO DMBO_FUNCTION (FUNCTION_CODE, FUNCTION_NAME, FUNCTION_LEVEL, FUNCTION_URL, FUNCTION_ORDER, PARENT_ID, FUNCTION_DISPLAY, STATUS, CREATED_BY)
SELECT 'ICON_CHANGE_STATUS', N'Đổi trạng thái icon', 2, NULL, 44,
       (SELECT FUNCTION_ID FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'ICON_MANAGEMENT'),
       0, 'ACTIVE', 'SYSTEM' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'ICON_CHANGE_STATUS');

INSERT INTO DMBO_FUNCTION (FUNCTION_CODE, FUNCTION_NAME, FUNCTION_LEVEL, FUNCTION_URL, FUNCTION_ORDER, PARENT_ID, FUNCTION_DISPLAY, STATUS, CREATED_BY)
SELECT 'ICON_FUNCTION_CODE_VIEW', N'Xem function code icon', 2, NULL, 45,
       (SELECT FUNCTION_ID FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'ICON_MANAGEMENT'),
       0, 'ACTIVE', 'SYSTEM' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DMBO_FUNCTION WHERE UPPER(FUNCTION_CODE) = 'ICON_FUNCTION_CODE_VIEW');

INSERT INTO DMBO_ROLE_FUNC (ROLE_ID, FUNCTION_ID, CREATE_USER)
SELECT R.ROLE_ID, F.FUNCTION_ID, 'SYSTEM'
FROM DMBO_ROLE R
JOIN DMBO_FUNCTION F ON UPPER(F.FUNCTION_CODE) IN (
    'ICON_MANAGEMENT', 'ICON_CREATE', 'ICON_UPDATE', 'ICON_DELETE', 'ICON_CHANGE_STATUS', 'ICON_FUNCTION_CODE_VIEW'
)
WHERE UPPER(R.ROLE_CODE) = 'SUPER_ADMIN'
  AND NOT EXISTS (
      SELECT 1 FROM DMBO_ROLE_FUNC RF
      WHERE RF.ROLE_ID = R.ROLE_ID AND RF.FUNCTION_ID = F.FUNCTION_ID
  );

COMMIT;
